
# image: Visual Studio 2015

environment:
  nodejs_version: "8"

platform:
  - x64

shallow_clone: true

# Install vcpkg and install deps
install:
  - cmd: git clone https://github.com/Microsoft/vcpkg.git
  - cmd: cd vcpkg
  - cmd: .\bootstrap-vcpkg.bat
  - cmd: .\vcpkg integrate install
  - cmd: vcpkg install openssl zlib libuv

build: off

build_script:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - cmd: cd .\nodejs
  - cmd: make.bat
