language: node_js

jobs:
  include:
    - stage: build-linux
      os: linux
      node_js: "node"
    - stage: build-osx
      osx_image: xcode7.3
      os: osx
      node_js: "node"

addons:
  apt:
    packages:
      - gcc
      - g++
      - libssl-dev
      - zlib1g-dev

before_install:
  - "if [ ${TRAVIS_OS_NAME} = 'osx' ]; then brew install --force openssl zlib libuv; fi"
  - "if [ ${TRAVIS_OS_NAME} = 'linux' ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt-get update && sudo apt-get install -y g++-4.8 && sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50; fi"

install:
  - "cd nodejs && make && cd .."

# Release to github under version tag
# https://stackoverflow.com/questions/23277391/how-to-publish-to-github-pages-from-travis-ci
script:
- if [[ $PUBLISH_BINARY == true ]]; then 
    node-pre-gyp package; 
  fi

# Cleanup
- cd nodejs && make clean && cd ..

# Make
# upload bindings to github as release
# Same for .appveyor for windows bindings
# setup npm install to install from github instead of just downloading from npm

# script: brew install --force openssl libuv && make && make install && make tests && time ./testsBin
