language: node_js

# Multiple stage build for linux and osx
jobs:
  include:
    - stage: build-linux
      os: linux
      node_js: "node"
    - stage: build-osx
      osx_image: xcode7.3
      os: osx
      node_js: "node"

# Install dependencies on linux. See below about g++-4.8
addons:
  apt:
    packages:
      - gcc
      - g++
      - libssl-dev
      - zlib1g-dev

# Install dependencies on osx, fix g++ on linux to be g++-4.8
before_install:
  - "if [ ${TRAVIS_OS_NAME} = 'osx' ]; then brew install --force openssl zlib libuv; fi"
  - "if [ ${TRAVIS_OS_NAME} = 'linux' ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt-get update && sudo apt-get install -y g++-4.8 && sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50; fi"

# Make
install:
  - "cd nodejs && make && cd .."

# Release to github if tagged: See docs: https://docs.travis-ci.com/user/deployment/releases/
# Note: The api_key: secure: is NOT the raw github api token. It is the encrptyed token generated
# by the travis cli 'encrypt' method. See these docs (there are separate docs for appveyor):
# https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/
# https://docs.travis-ci.com/user/encryption-keys/
deploy:
  provider: releases
  api_key:
    secure: GITHUB_OAUTH_API_KEY_ENCRYPTED
  file_glob: true
  file: ./nodejs/*.node
  skip_cleanup: true
  on:
    tags: true
